include:
  base_path: ./config/DASM/AS/htsat-sed/train1.yaml
  keys: [feature, dataset, class_loss]

generals:
  warn: False                          # show warnings
  savepsds: False                       # save psds data
  test_on_public_eval: False           # change test dataset to DESED Reak public_eval (default dataset is DESED Real Validation)
  load_from_existed_path: False         # Load model in existed path instead of creating a new one if true
  finetune_mlm: False
  test_only: False                     # perform test without training, for the model saved in save_folder
  validation_interval: 1
  log_level: DEBUG

training:
  batch_size: 36
  batch_size_val: 72
  num_workers: 6
  seed: 21
  clip_grad: True
  # =============================
  scheduler:
    scheduler_name: ExponentialDown
    n_epochs: 8                        #>> number of epochs to run
    n_epochs_cut: 2                  #>> number of epochs used for exponential warmup
    exponent: -1.5
    lr_warmup_epochs: 2
    lr_warmup_rate: 0.1
  # =============================
  w_AT: 0.5
  median_window: 5


Maskformer_HTSAT:
  init_kwargs:
    backbone_param:
      embed_dim: 768
      pretrain_model_path: ./exps/mm2025/AS/archive/model/htast_mga.pt
      lora_config: 
    cnn_param:
      n_in_channel: 1
      activation: cg
      conv_dropout: 0.5
      kernel_size: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
      padding: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      stride: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      nb_filters: [ 16, 16, 32, 32, 64, 64, 128, 128, 256, 256]
      pooling: [ [ 2, 2 ], [1, 1], [ 2, 2 ],[1, 1], [ 1, 2 ], [ 1, 2], [ 1, 2 ], [ 1, 1 ], [ 1, 2], [1, 1] ]
    at_param:
      at_decoder_layer: 2
      query_projector: True
      out_type: "sigmoid"
      query_dim: 1024
      query: ./exps/mm2025/AS/archive/text_embedding/mga_clap/embedding.pt

    backbone_upsample_ratio: 15.626                     # decode ratio in local gru decoder
    decoder_dim: 384
    num_heads: 12
    decoder: "conformer"
    decoder_layer_num: 2
    decoder_pos_emd_len: 500
    decoder_expand_rate: 1
    class_num: 407

  train_kwargs:
    # windows parameters
    encoder_win: False    # constant
    # temperature parameters
    temp_w: 1
    
  val_kwargs:
    # windows parameters
    encoder_win: False
    temp_w: 0.5

  test_kwargs:
    # windows parameters
    encoder_win: False
    temp_w: 0.5


opt:
  param_groups: 
    cnn:
      lr: 3.0e-4
      weight_decay: 1.0e-4
    backbone:
      lr: 0 
      weight_decay: 1.0e-4
      freeze_layer: 0
    sed_decoder: 
      lr: 3.0e-4 
      weight_decay: 1.0e-4
    at_decoder:
      lr: 3.0e-4 
      weight_decay: 1.0e-4
    query:
      lr: 0
      weight_decay: 1.0e-4
    head:
      lr: 3.0e-4
      weight_decay: 1.0e-4      