include:
  base_path: ./config/DASM/AS/htsat-sed/train1.yaml
  keys: [feature, HTSAT_CNN, dataset, class_loss]

generals:
  savepsds: False                      # save psds data
  test_on_public_eval: False           # change test dataset to DESED Reak public_eval (default dataset is DESED Real Validation)
  load_from_existed_path: True         # Load model in existed path instead of training from scratch if true
  finetune_mlm: False
  test_only: True                     # perform test without training, for the model saved in save_folder
  validation_interval: 1
  log_level: DEBUG

training:
  batch_size: 36
  batch_size_val: 72
  num_workers: 6
  seed: 21
  clip_grad: True
  # =============================
  scheduler:
    scheduler_name: ExponentialDown
    n_epochs: 6                        #>> number of epochs to run
    n_epochs_cut: 2                  #>> number of epochs used for exponential warmup
    exponent: -1.5
    lr_warmup_epochs: 2
    lr_warmup_rate: 0.1
  # =============================
  median_window: 5

opt:
  param_groups: 
    cnn:
      lr: 3.0e-4
      weight_decay: 1.0e-4
    backbone:
      lr: 1.5e-5
      weight_decay: 1.0e-4
    sed_decoder: 
      lr: 3.0e-4 
      weight_decay: 1.0e-4
    head:
      lr: 3.0e-4
      weight_decay: 1.0e-4      