include:
  base_path: ./config/DASM/AS/htsat/mix_query/train1.yaml
  keys: [feature, dataset, class_loss, Maskformer_HTSAT]

generals:
  warn: False                          # show warnings
  savepsds: False                       # save psds data
  test_on_public_eval: False           # change test dataset to DESED Reak public_eval (default dataset is DESED Real Validation)
  load_from_existed_path: True         # Load model in existed path instead of creating a new one if true
  finetune_mlm: False
  test_only: False                    # perform test without training, for the model saved in save_folder
  validation_interval: 1
  log_level: DEBUG

training:
  batch_size: 36
  batch_size_val: 72
  num_workers: 6
  seed: 21
  clip_grad: True
  # =============================
  scheduler:
    scheduler_name: ExponentialDown
    n_epochs: 6                        #>> number of epochs to run
    n_epochs_cut: 2                  #>> number of epochs used for exponential warmup
    exponent: -1.5
    lr_warmup_epochs: 2
    lr_warmup_rate: 0.1
  # =============================
  val_thresholds: [0.5]                # thresholds used to compute f1 intersection in validation.
  n_test_thresholds: 50                # number of thresholds used to compute psds in test
  w_AT: 0.5
  decode_weak_valid: 1                 # weak prediction masking on strong prediction,
  decode_weak_test: 1                  # 0: no weak prediction used, 1: weak prediction masking, 2: weak SED
  # Notice that the real length of median windows is aproximately 6 times than this(see setting.py for details).
  median_window: 5


opt:
  param_groups: 
    cnn:
      lr: 3.0e-4
      weight_decay: 1.0e-4
    backbone:
      lr: 1.5e-5 
      weight_decay: 1.0e-4
      freeze_layer: 0
    sed_decoder: 
      lr: 3.0e-4 
      weight_decay: 1.0e-4
    at_decoder:
      lr: 3.0e-4 
      weight_decay: 1.0e-4
    query:
      lr: 0
      weight_decay: 1.0e-4
    head:
      lr: 3.0e-4
      weight_decay: 1.0e-4      